default_provider = "age"

[providers.age]
type = "age"
recipients = ["age1nlqfv0ptcfs7ssuuq8c06nprslcvwg9qpt6kf0ex20jhnknjmsqsrqf96k"]

[secrets]
CARGO_REGISTRY_TOKEN= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXd2xTVHhWbWtrSjkybFdLZisyaXZSeEc1QVNTeE03a1lQV2pPWWw3V0g0CnZCMit2Wmo0Z0Q2MjU3a21JR2Q1a0FHZm5LbFFMSVh0bmN6K3d3ZFRObGMKLT4geml8LWdyZWFzZSBPCjMxT1BCQTFFWnhjMjFiYzVDeTFrMEcrdGtxTTN6Y0UwdTVwNXRNNjdlT3JJTmp3Q085aU1SV3FhanlSQ3VGb3AKbUtqNU5aV0M1TlFrNUlLeVZKY1pZTTIwbXBFZQotLS0gYnlVakNrVS9nVERtaktJdGJYSlVnR3h6VkJpTmIwVUx5Z1RPaFJCSE1iOApRLTQqEK6XGBWWvRSwH8bBtVNNpsw1uikM7/c6FIBer3aU+rc/mIZhGcPYaWwDp61zDmKGgfkS5TnwKvt7boS/Kr7X" }
NPM_TOKEN = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeDZPMUpLbTAwT3k4RlZoL0dKOFd2SXQ5bFpoaU15aUY3MG9SOXZkZUZJCndXYy9GZWxzVWVEUGxTbnhwZVhZSVM1b0JmV3Y4R2JUczFiL3lrUUhWdUUKLT4gJHYvK2pzLWdyZWFzZSB3MiArQlknClRRVU5nTGszZkJPdWpEQzh0bm5NeFg2Y2NOdFZsemJHaDk5WGV0MXRwY1RrdUcydUpqUW55N0ZWMURhcVhNZmYKUWxQLzlPTzk4RUMvV0JHVUlOYkZJeVZnSW1pbWlYTTB3S3JRTklXcWFKdDg3SXlDNnNSbFV4MAotLS0gYXRyNUtXeUhVVVpaaUlmSmZuSndmU3haZ3N5dFNFUTQzbDg5VG1pSEs1VQr/rd6AiaSv6zk7DeQ4/29CFiZWXSDDQ/o1A0xshb8LnHco1D9UeIUKNhFmzeQfBPHlxpvXXLCr+dnMSF8bSBq7afYjHmjX0lo=" }

